$(document).ready(function(){
    $("#fadeButtonShow").click(function(){
        $("#ARAbout").fadeIn();
    });
});
$(document).ready(function(){
    $("#fadeButtonHide").click(function(){
        $("#ARAbout").fadeOut();
    });
});