$(document).ready(function(){
    $("#fadeButtonShow").click(function(){
        $("#chat_system").fadeIn();
    });
});
$(document).ready(function(){
    $("#fadeButtonHide").click(function(){
        $("#chat_system").fadeOut();
    });
});
